# Generated by Django 2.2.6 on 2019-11-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='telefono',
            field=models.IntegerField(max_length=10),
        ),
    ]
