# Generated by Django 2.2.6 on 2019-11-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_auto_20191101_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntario',
            options={'ordering': ['apellido']},
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='enail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='rut',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='VoluntarioInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voluntario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunidad.Voluntario')),
            ],
        ),
    ]
