# Generated by Django 2.2.6 on 2019-11-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_auto_20191111_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoluntarioInstance',
        ),
    ]
